[GRUPO 17] Requisito 11
tryber/sd-014-a-project-frontend-online-store pull request #403
Opened 2021-09-22 21:53 UTC by saulolima-c

2021-09-22 23:13 UTC, VSSSP requested changes
Opa! Vamos verificar isso amanhã, parece que ta substituindo muitos arquivos.

2021-09-22 23:14 UTC, pallyoliveira requested changes
gaaalera, vamo ter que rever antes de mergear, porque vai da uns conflitos. vemos amanhã

2021-09-23 15:32 UTC, VSSSP approved these changes

2021-09-23 15:46 UTC, pallyoliveira approved these changes

2021-09-23 15:46 UTC, merged